# Generated by Django 5.2.1 on 2025-05-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricao',
            options={'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
    ]
