# Generated by Django 5.2.1 on 2025-05-31 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenapp', '0002_alter_inscricao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
